kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker-k8s
  template:
    metadata:
      labels:
        app: react-docker-k8s
    spec:
      containers:
      - name: react-docker-k8s
        image: selvas82/react-docker-k8s
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: react-docker-k8s
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32700
  selector:
    app: react-docker-k8s